# Generated by Django 6.0 on 2025-12-27 09:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='hr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('CompanyName', models.CharField(max_length=200)),
                ('salaryLow', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('salaryHigh', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('applycount', models.IntegerField(default=0)),
                ('lastDateToApply', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='candidateApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_level', models.CharField(choices=[('SEE', 'SEE (School Leaving Exam)'), ('SLC', 'SLC (School Leaving Certificate)'), ('PLUS2', '+2 (Higher Secondary)'), ('DIPLOMA', 'Diploma'), ('BACHELOR', 'Bachelor'), ('MASTERS', 'Masters')], default='BACHELOR', max_length=20)),
                ('passingYear', models.IntegerField()),
                ('yearOfExp', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('resume', models.FileField(upload_to='resume')),
                ('support_documents', models.FileField(blank=True, help_text='Optional: Academic documents (PDF only, max 5MB)', null=True, upload_to='support_docs')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('shortlisted', 'shortlisted'), ('rejected', 'rejected')], default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.jobpost')),
            ],
            options={
                'unique_together': {('user', 'job')},
            },
        ),
        migrations.CreateModel(
            name='ShortlistedCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortlisted_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hr.candidateapplication')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.jobpost')),
            ],
        ),
    ]
