# Generated by Django 6.0 on 2026-02-07 07:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='hr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recruiter Account',
                'verbose_name_plural': 'Recruiter Accounts',
            },
        ),
        migrations.CreateModel(
            name='HRProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='hr_logos/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='hr_covers/')),
                ('industry', models.CharField(choices=[('technology', 'Technology'), ('finance', 'Finance'), ('healthcare', 'Healthcare'), ('retail', 'Retail'), ('manufacturing', 'Manufacturing'), ('education', 'Education'), ('hospitality', 'Hospitality'), ('real_estate', 'Real Estate'), ('banking', 'Banking'), ('insurance', 'Insurance'), ('consulting', 'Consulting'), ('logistics', 'Logistics'), ('media', 'Media & Entertainment'), ('other', 'Other')], max_length=50)),
                ('company_type', models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('ngo', 'NGO'), ('startup', 'Startup'), ('government', 'Government')], default='private', max_length=20)),
                ('employee_size', models.CharField(choices=[('1-10', '1 - 10 employees'), ('11-50', '11 - 50 employees'), ('51-200', '51 - 200 employees'), ('201-500', '201 - 500 employees'), ('501-1000', '501 - 1000 employees'), ('1000+', '1000+ employees')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('location', models.CharField(max_length=200)),
                ('about_company', models.TextField(help_text='Describe your company')),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('CompanyName', models.CharField(max_length=200)),
                ('salaryLow', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('salaryHigh', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('applycount', models.IntegerField(default=0)),
                ('lastDateToApply', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('employment_type', models.CharField(blank=True, choices=[('full-time', 'Full-time'), ('part-time', 'Part-time'), ('internship', 'Internship'), ('contract', 'Contract'), ('freelance', 'Freelance')], default='full-time', max_length=20, null=True)),
                ('work_mode', models.CharField(blank=True, choices=[('on-site', 'On-site'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], default='on-site', max_length=20, null=True)),
                ('required_experience', models.CharField(choices=[('no-experience', 'No experience required'), ('6-months', '6 months'), ('1-year', '1 year'), ('2-years', '2 years'), ('3-years', '3 years'), ('4-years', '4 years'), ('5-plus-years', '5+ years'), ('others', 'Others')], default='no-experience', help_text='Select required years of experience', max_length=50)),
                ('required_experience_custom', models.CharField(blank=True, help_text='Custom experience requirement (e.g., 1.5 years)', max_length=100, null=True)),
                ('required_education', models.CharField(choices=[('no-education', 'No education required'), ('see', 'SEE'), ('slc', 'SLC'), ('plus2', '+2'), ('diploma', 'Diploma'), ('bachelor', 'Bachelor'), ('master', 'Master'), ('phd', 'PhD')], default='no-education', help_text='Select required education level', max_length=50)),
                ('required_skills', models.TextField(blank=True, help_text='Comma-separated skills (e.g., Python, SQL, Communication)', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SelectedCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='candidate.candidateapplication')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.jobpost')),
            ],
        ),
        migrations.CreateModel(
            name='ShortlistedCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortlisted_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='candidate.candidateapplication')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.jobpost')),
            ],
        ),
    ]
