# Generated by Django 6.0 on 2026-02-07 12:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HRProfile',
            new_name='RecruiterProfile',
        ),
        migrations.AlterModelOptions(
            name='recruiterprofile',
            options={'verbose_name': 'Recruiter Profile', 'verbose_name_plural': 'Recruiter Profiles'},
        ),
        migrations.AlterModelTable(
            name='recruiterprofile',
            table='hr_hrprofile',
        ),
    ]
