# Generated by Django 6.0 on 2025-12-27 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateapplication',
            name='education_level',
            field=models.CharField(choices=[('SEE', 'SEE (School Leaving Exam)'), ('SLC', 'SLC (School Leaving Certificate)'), ('+2', '+2 (Higher Secondary)'), ('DIPLOMA', 'Diploma'), ('BACHELOR', 'Bachelor'), ('MASTERS', 'Masters')], default='BACHELOR', max_length=20),
        ),
        migrations.CreateModel(
            name='SelectedCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hr.candidateapplication')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.jobpost')),
            ],
        ),
    ]
