# Generated by Django 6.0 on 2025-12-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_alter_candidateapplication_education_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateapplication',
            name='education_level',
            field=models.CharField(choices=[('SEE', 'SEE (School Leaving Exam)'), ('SLC', 'SLC (School Leaving Certificate)'), ('PLUS2', '+2 (Higher Secondary)'), ('DIPLOMA', 'Diploma'), ('BACHELOR', 'Bachelor'), ('MASTERS', 'Masters')], default='BACHELOR', max_length=20),
        ),
    ]
