# Generated by Django 6.0 on 2025-12-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_alter_candidateapplication_education_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('shortlisted', 'shortlisted'), ('rejected', 'rejected'), ('selected', 'selected')], default='pending', max_length=20),
        ),
    ]
