# Generated by Django 6.0 on 2026-01-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_alter_candidateapplication_passingyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateapplication',
            name='education_level',
            field=models.CharField(choices=[('SEE', 'SEE (Secondary Education Examination)'), ('SLC', 'SLC (School Leaving Certificate)'), ('PLUS2', '+2 (Higher Secondary)'), ('DIPLOMA', 'Diploma'), ('BACHELOR', 'Bachelor'), ('MASTERS', 'Masters')], default='BACHELOR', max_length=20),
        ),
    ]
