# Generated by Django 6.0 on 2026-01-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_alter_candidateapplication_education_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('full-time', 'Full-time'), ('part-time', 'Part-time'), ('internship', 'Internship'), ('contract', 'Contract'), ('freelance', 'Freelance')], default='full-time', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='work_mode',
            field=models.CharField(blank=True, choices=[('on-site', 'On-site'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], default='on-site', max_length=20, null=True),
        ),
    ]
