# Generated by Django 6.0 on 2026-01-17 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_jobpost_employment_type_jobpost_work_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HRProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='hr_logos/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='hr_covers/')),
                ('industry', models.CharField(choices=[('technology', 'Technology'), ('finance', 'Finance'), ('healthcare', 'Healthcare'), ('retail', 'Retail'), ('manufacturing', 'Manufacturing'), ('education', 'Education'), ('hospitality', 'Hospitality'), ('real_estate', 'Real Estate'), ('banking', 'Banking'), ('insurance', 'Insurance'), ('consulting', 'Consulting'), ('logistics', 'Logistics'), ('media', 'Media & Entertainment'), ('other', 'Other')], max_length=50)),
                ('company_type', models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('ngo', 'NGO'), ('startup', 'Startup'), ('government', 'Government')], default='private', max_length=20)),
                ('employee_size', models.CharField(choices=[('1-10', '1 - 10 employees'), ('11-50', '11 - 50 employees'), ('51-200', '51 - 200 employees'), ('201-500', '201 - 500 employees'), ('501-1000', '501 - 1000 employees'), ('1000+', '1000+ employees')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('location', models.CharField(max_length=200)),
                ('about_company', models.TextField(help_text='Describe your company')),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
