# Generated by Django 6.0 on 2026-02-05 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_hrprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hr',
            options={'verbose_name': 'Recruiter Account', 'verbose_name_plural': 'Recruiter Accounts'},
        ),
    ]
