# Generated by Django 6.0 on 2026-01-07 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='candidate_photos/')),
                ('job_preference_title', models.CharField(help_text='e.g., Document Officer', max_length=200)),
                ('preferred_job_level', models.CharField(choices=[('top', 'Top Level'), ('senior', 'Senior Level'), ('mid', 'Mid Level'), ('junior', 'Junior/Entry Level'), ('internship', 'Internship')], max_length=20)),
                ('preferred_job_type', models.CharField(choices=[('fulltime', 'Full Time'), ('parttime', 'Part Time')], max_length=20)),
                ('work_experience', models.IntegerField(default=0)),
                ('education_level', models.CharField(choices=[('see', 'SEE (Secondary Education Examination)'), ('slc', 'SLC (School Leaving Certificate)'), ('plus2', '+2 (Higher Secondary)'), ('diploma', 'Diploma'), ('bachelor', 'Bachelor'), ('masters', 'Masters')], max_length=20)),
                ('course_or_program', models.CharField(help_text='e.g., BIM', max_length=200)),
                ('gpa_percentage_type', models.CharField(choices=[('gpa', 'GPA (out of 10)'), ('percentage', 'Percentage (out of 100)')], max_length=10)),
                ('gpa_percentage_value', models.FloatField()),
                ('school_college_name', models.CharField(max_length=200)),
                ('graduation_year', models.IntegerField()),
                ('skills', models.TextField(help_text='e.g., Public Speaking, Computer Operation')),
                ('languages', models.TextField(help_text='e.g., Nepali, English')),
                ('social_account_name_1', models.CharField(blank=True, max_length=100, null=True)),
                ('social_account_url_1', models.URLField(blank=True, null=True)),
                ('social_account_name_2', models.CharField(blank=True, max_length=100, null=True)),
                ('social_account_url_2', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
