# Generated by Django 6.0 on 2026-02-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='career_summary',
            field=models.TextField(blank=True, help_text='Short career summary / mini bio', null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='job_interest',
            field=models.TextField(blank=True, help_text='Job interests as comma-separated text, e.g., Software Developer, Data Analyst', null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='preferred_industry',
            field=models.CharField(blank=True, choices=[('it', 'IT'), ('fintech', 'FinTech'), ('ecommerce', 'E-Commerce'), ('healthcare', 'Healthcare'), ('banking_finance', 'Banking & Finance'), ('education', 'Education'), ('telecommunications', 'Telecommunications'), ('manufacturing', 'Manufacturing'), ('engineering', 'Engineering'), ('digital_marketing', 'Digital Marketing'), ('management', 'Management / Managers'), ('real_estate', 'Real Estate'), ('insurance', 'Insurance')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='work_experience_description',
            field=models.TextField(blank=True, help_text='Brief description of your work experience', null=True),
        ),
    ]
