# Generated by Django 6.0 on 2026-01-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_candidateprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='profile_photo',
            field=models.FileField(blank=True, null=True, upload_to='candidate_photos/'),
        ),
    ]
