# Generated by Django 6.0 on 2026-01-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_alter_candidateprofile_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='gpa_percentage_type',
            field=models.CharField(choices=[('gpa_4', 'GPA (out of 4)'), ('gpa_10', 'GPA (out of 10)'), ('percentage', 'Percentage (out of 100)')], max_length=10),
        ),
    ]
