# Generated by Django 6.0 on 2026-02-05 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0008_alter_candidateprofile_graduation_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='isshortlisted',
            options={'verbose_name': 'Shortlist Notification', 'verbose_name_plural': 'Shortlist Notifications'},
        ),
        migrations.AlterModelOptions(
            name='myapplyjoblist',
            options={'verbose_name': 'Job Application Tracker', 'verbose_name_plural': 'Job Application Trackers'},
        ),
    ]
