# Generated by Django 6.0 on 2026-02-05 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0009_alter_isshortlisted_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('pending', 'Pending Verification'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('reason_for_suspension', models.TextField(blank=True, null=True)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('suspended_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Candidate Account',
                'verbose_name_plural': 'Candidate Accounts',
                'ordering': ('-created_at',),
            },
        ),
        migrations.DeleteModel(
            name='IsShortlisted',
        ),
    ]
